/**
 * themes.js
 * Tokens de diseño para modo oscuro y modo claro.
 * Cada clave es una clase de Tailwind lista para usar en JSX.
 */

export const THEMES = {
  dark: {
    bg:               "bg-zinc-950",
    surface:          "bg-zinc-900/40",
    surfaceHow:       "bg-zinc-900/60",
    surfaceFormula:   "bg-zinc-950",
    surfaceStep:      "bg-zinc-800/50",
    surfaceDev:       "bg-zinc-900/20",
    border:           "border-zinc-800",
    borderStep:       "border-zinc-700/50",
    borderFormula:    "border-zinc-700",
    borderDevBtn:     "border-zinc-700 hover:border-zinc-600",
    divider:          "bg-zinc-800",
    text:             "text-zinc-100",
    textSub:          "text-stone-500",
    textMuted:        "text-zinc-600",
    textLabel:        "text-amber-400/70",
    textAccent:       "text-amber-400",
    textAccentSoft:   "text-amber-300",
    textTaskName:     "text-zinc-100",
    textMeta:         "text-zinc-500",
    textAnxLabel:     "text-zinc-600",
    textAnxVal:       "text-zinc-500",
    textDevBtn:       "text-zinc-400 hover:text-zinc-200",
    textClear:        "text-zinc-600 hover:text-red-400",
    textToggle:       "text-zinc-500 hover:text-amber-400",
    inputBg:          "bg-zinc-800",
    inputBorder:      "border-zinc-700",
    inputText:        "text-zinc-100",
    inputPlaceholder: "placeholder-zinc-600",
    inputFocus:       "focus:border-amber-400/60",
    inputColorScheme: "[color-scheme:dark]",
    sliderEmpty:      "#3f3f46",
    sliderThumbBorder:"border-zinc-900",
    anxietyTrack:     "bg-zinc-700",
    planBg:           "bg-zinc-900/60",
    planBorder:       "border-amber-400/20",
    planBarBg:        "bg-zinc-800",
    howBorder:        "border-amber-400/20",
    taskNormal:       "border-zinc-700/50 bg-zinc-800/30",
    taskUrgent:       "border-orange-400/20 bg-orange-950/10",
    taskOverdue:      "border-red-500/30 bg-red-950/20",
    urgencyNormal:    "text-zinc-400",
    deleteBtn:        "text-zinc-600 hover:text-red-400",
    toggleBorder:     "border-zinc-700 hover:border-amber-400/40",
  },
  light: {
    bg:               "bg-stone-50",
    surface:          "bg-white",
    surfaceHow:       "bg-amber-50/70",
    surfaceFormula:   "bg-amber-50",
    surfaceStep:      "bg-white",
    surfaceDev:       "bg-stone-100/60",
    border:           "border-stone-200",
    borderStep:       "border-stone-200",
    borderFormula:    "border-amber-200",
    borderDevBtn:     "border-stone-300 hover:border-stone-400",
    divider:          "bg-stone-200",
    text:             "text-stone-900",
    textSub:          "text-stone-500",
    textMuted:        "text-stone-400",
    textLabel:        "text-amber-600/80",
    textAccent:       "text-amber-600",
    textAccentSoft:   "text-amber-500",
    textTaskName:     "text-stone-900",
    textMeta:         "text-stone-500",
    textAnxLabel:     "text-stone-400",
    textAnxVal:       "text-stone-500",
    textDevBtn:       "text-stone-500 hover:text-stone-800",
    textClear:        "text-stone-400 hover:text-red-500",
    textToggle:       "text-stone-500 hover:text-amber-600",
    inputBg:          "bg-white",
    inputBorder:      "border-stone-300",
    inputText:        "text-stone-900",
    inputPlaceholder: "placeholder-stone-400",
    inputFocus:       "focus:border-amber-400",
    inputColorScheme: "[color-scheme:light]",
    sliderEmpty:      "#d6d3d1",
    sliderThumbBorder:"border-white",
    anxietyTrack:     "bg-stone-200",
    planBg:           "bg-amber-50/60",
    planBorder:       "border-amber-300/50",
    planBarBg:        "bg-stone-200",
    howBorder:        "border-amber-300/50",
    taskNormal:       "border-stone-200 bg-stone-50/80",
    taskUrgent:       "border-orange-300/60 bg-orange-50",
    taskOverdue:      "border-red-300/60 bg-red-50",
    urgencyNormal:    "text-stone-400",
    deleteBtn:        "text-stone-300 hover:text-red-500",
    toggleBorder:     "border-stone-300 hover:border-amber-400/60",
  },
};
